#!/usr/bin/env python3

import argparse

from datetime import datetime
from os.path import join

from twspam import retry
from twspam.config import Config
from twspam.logger import Logger
from twspam.sudo import runasroot
from twspam_apps.twitter.linux_ff import TwitterLinuxFirefoxApp
from twspam_apps.twitter.windows_cr import TwitterWindowsChromeApp
from twspam_apps.twitter.windows_ff import TwitterWindowsFirefoxApp


logger = Logger(__name__)
main_config = Config('twspam')


if __name__ == '__main__':
    parser = argparse.ArgumentParser("Generate Twitter sessions")
    parser.add_argument(
        'profile', choices=['linux_ff', 'windows_cr', 'windows_ff'],
        help="profile to run")
    parser.add_argument(
        '-s', '--num-sessions', type=int, default=1,
        help="number of sessions to run")
    parser.add_argument(
        '-a', '--num-attempts', type=int, default=5,
        help="number of attempts per session")
    parser.add_argument(
        'output', nargs='?', default='.',
        help="output directory")
    args = parser.parse_args()
    runasroot()
    if args.profile == 'linux_ff':
        app = TwitterLinuxFirefoxApp()
    elif args.profile == 'windows_cr':
        app = TwitterWindowsChromeApp()
    else:
        app = TwitterWindowsFirefoxApp()
    for i in range(args.num_sessions):
        logger.notice("Run session {}/{}", i + 1, args.num_sessions)
        now = datetime.now()
        session_dirname = now.strftime(main_config.session_dirname_fmt)
        session_dirpath = join(args.output, session_dirname)
        for _ in retry.n_times(args.num_attempts):
            try:
                app.run(session_dirpath)
            except retry.RetryError:
                continue
            break
